In [1]:
import numpy as np
# numpy.linalg模块包含线性代数的函数。使用这个模块，可以计算逆矩阵、求特征值、解线性方程组以及求解行列式等
from numpy.linalg import *

p1 = np.array([[1,2],[3,4]])
y = np.array([[5],[9]])
print(solve(p1,y))
p2 = np.array([[1,3,4],[2,3,4]])
print(solve(p1,p2))
p3 = np.array([[1,0,3],[2,5,4],[3,4,5]])
p4 = np.array([[1,3,4],[2,7,4],[6,5,8]])
print(solve(p3,p4))

[[-1.]
 [ 3.]]
[[ 0.  -3.  -4. ]
 [ 0.5  3.   4. ]]
[[ 4.75       -3.          3.        ]
 [-0.5         1.         -0.66666667]
 [-1.25        2.          0.33333333]]


In [4]:
p1 = np.random.rand(4,4)
p2 = np.random.rand(4,2)
p3 = solve(p1, p2)

In [6]:
np.matmul(p1, p3)

array([[0.4664222 , 0.42573758],
       [0.06401935, 0.94296356],
       [0.40325476, 0.03986015],
       [0.13993707, 0.2593246 ]])

In [7]:
p2

array([[0.4664222 , 0.42573758],
       [0.06401935, 0.94296356],
       [0.40325476, 0.03986015],
       [0.13993707, 0.2593246 ]])

In [141]:
poly1 = 8
poly2 = 6
p1 = np.random.rand(poly1, poly2)
p2 = np.random.rand(poly2, 1)

In [142]:
diff = poly1 - poly2
randx = np.random.rand(diff,)
p1temp = p1[diff:,]
p2temp = p2

In [143]:
for i in range(diff):
    p2temp -= np.transpose(np.expand_dims(np.dot(p1[i], randx[i]), axis=0))

In [144]:
x2 = solve(p1temp, p2temp)

In [146]:
randx

array([0.00562684, 0.03255569])

In [147]:
x2

array([[-0.13885633],
       [ 0.32463845],
       [-0.07508607],
       [ 0.80376875],
       [-0.82872837],
       [ 2.27072163]])

In [149]:
x = np.concatenate((np.transpose(np.expand_dims(randx, axis=0)), x2))

In [162]:
x

array([[ 0.00562684],
       [ 0.03255569],
       [-0.13885633],
       [ 0.32463845],
       [-0.07508607],
       [ 0.80376875],
       [-0.82872837],
       [ 2.27072163]])

In [163]:
p1

array([[0.41170393, 0.25547382, 0.56855646, 0.58444381, 0.65065264,
        0.2542358 ],
       [0.89073794, 0.05460775, 0.81375586, 0.17154445, 0.84296302,
        0.78346673],
       [0.26684038, 0.48332624, 0.88691717, 0.12558318, 0.89654668,
        0.25132237],
       [0.80278063, 0.47489321, 0.64873296, 0.80911284, 0.99161269,
        0.1869123 ],
       [0.86196187, 0.5961772 , 0.34281581, 0.06206189, 0.29702153,
        0.30479682],
       [0.90880211, 0.23052282, 0.23175295, 0.4583192 , 0.89692369,
        0.34453065],
       [0.4996218 , 0.26109056, 0.71348034, 0.72098536, 0.79754403,
        0.41001904],
       [0.59525404, 0.0010572 , 0.89596926, 0.80912791, 0.6038902 ,
        0.08119908]])

In [167]:
result = []
for i in range(poly2):
    temp = 0
    for j in range(poly1):
        temp += x[j][0] * p1[j][i]
    result.append(temp)

In [168]:
result

[1.8582270453837715,
 0.016820881904627532,
 1.7208916289426348,
 1.8576303398125684,
 1.6374650071869352,
 0.15134112248362705]

In [169]:
p2

array([[-0.01811202],
       [ 0.24697446],
       [ 0.54395445],
       [ 0.33865197],
       [ 0.81140919],
       [ 0.18468489]])